data_source:
  network: "ethereum"
  rpc:
    url: "${RPC_URL}"
providers:
  etherscan:
    api_key: "${ETHERSCAN_API_KEY}"

db:
  driver: "sqlite"
  sqlite_path: "sandbox_whales.db"

ingestion:
  start_block: 21000000
  end_block: 21001000
  max_retries: 3
  backoff_seconds: 1.5

checkpoint:
  path: "checkpoint.json"
