name: smoke

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pydantic pyyaml

      - name: run smoke tests
        run: |
          pytest -q tests/test_meta_sanity.py tests/test_config_load.py
